"""
AfriGuard Pydantic schemas — GeneratedPrompt
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class PromptStatus(str, Enum):
    PENDING = "pending_response"
    GENERATED = "generated"
    FILTERED_OUT = "filtered_out"
    APPROVED = "approved"
    REJECTED = "rejected"


class GeneratedPrompt(BaseModel):
    """A prompt generated by the pipeline, ready for response generation."""

    id: str = Field(description="UUID")
    language: str = Field(description="Target language name")
    language_code: str = Field(description="ISO language code")
    harm_category: str = Field(description="Harm category ID (e.g. 'H01')")
    harm_category_name: str = Field(description="Human-readable harm category name")
    severity: str = Field(description="Severity level: S1, S2, S3, or S4")
    subcategory: str | None = Field(default=None, description="Specific subcategory within harm category")

    # Prompt content
    prompt_text: str = Field(description="The generated user-facing prompt text in the target language")
    system_prompt_used: str = Field(description="Full system prompt sent to the model")

    # Provenance
    prompt_template_id: str = Field(description="Template ID used (e.g. 'H01_v1')")
    prompt_template_version: str = Field(description="Semver of the template")
    prompt_template_hash: str = Field(description="SHA-256 of the template content")
    seed_document_ids: list[str] = Field(
        default_factory=list, description="IDs of seed documents injected as context"
    )
    legal_context_used: str | None = Field(
        default=None, description="Legal text snippet used as conditioning"
    )
    entities_injected: list[str] = Field(
        default_factory=list, description="Cultural entity names injected into the prompt"
    )

    # Generation metadata
    model_used: str = Field(description="Model used to generate this prompt")
    generation_params: dict[str, Any] = Field(
        default_factory=dict, description="Model parameters (temperature, etc.)"
    )
    prompt_tokens: int = Field(default=0, description="Tokens used in the prompt call")
    completion_tokens: int = Field(default=0, description="Tokens in the completion")
    cost_usd: float = Field(default=0.0, description="Estimated USD cost")

    status: PromptStatus = Field(default=PromptStatus.PENDING)
    created_at: datetime = Field(description="Generation timestamp")
    run_id: str = Field(description="Pipeline run ID (for grouping batch generations)")

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}
        use_enum_values = True
